services:
  - type: web
    name: wildlife-collision-backend
    runtime: python
    plan: starter
    region: frankfurt

    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/run_api.py

    envVars:
      - key: MONGODB_URI
        sync: false

      - key: DIGITRAFFIC_API_URL
        value: https://tie.digitraffic.fi/api/v1

      - key: OPEN_METEO_API_URL
        value: https://api.open-meteo.com/v1

      - key: PYTHONUNBUFFERED
        value: "1"

    autoDeploy: true
    healthCheckPath: /health